apiVersion: apps/v1
kind: Deployment
metadata:
 name: dind-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: dind
          image: "docker:dind"
          imagePullPolicy: Always
          command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Directory
